# Generated by Django 4.1.7 on 2024-01-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0002_remove_userinfo_user_userinfo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='surname',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='soy isim'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='isim'),
        ),
    ]
