# Generated by Django 4.1.7 on 2024-01-09 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='additional_images')),
            ],
        ),
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainimg', models.ImageField(blank=True, upload_to='Anaresim', verbose_name='Anaresim')),
                ('additional_images', models.ManyToManyField(blank=True, to='myApp.additionalimage')),
            ],
        ),
        migrations.AddField(
            model_name='additionalimage',
            name='hotels',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.hotel', verbose_name='oteller'),
        ),
    ]
