# Generated by Django 4.1.7 on 2024-01-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_hotel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Otel Fiyatı'),
        ),
    ]
