# Generated by Django 4.1.7 on 2024-01-09 13:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_hotel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
