# Generated by Django 4.1.7 on 2024-01-09 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_hotel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalimage',
            name='hotels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.hotel', verbose_name='oteller'),
        ),
    ]
