# Generated by Django 4.1.7 on 2024-01-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_hotel_hotellocationmapbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotellocationmapbox',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Otel Konumu kutu'),
        ),
    ]
