# Generated by Django 4.1.7 on 2024-01-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0020_alter_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Yorum başlık'),
        ),
    ]
