# Generated by Django 4.1.7 on 2024-01-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='name',
            field=models.TextField(blank=True, max_length=20, null=True, verbose_name='isim'),
        ),
    ]
