# Generated by Django 4.1.7 on 2024-01-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0004_userinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='email'),
        ),
    ]
