# Generated by Django 5.0.1 on 2024-01-19 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0008_baskets_date_alter_baskets_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='baskets',
            name='person',
            field=models.IntegerField(blank=True, max_length=20, null=True, verbose_name='Kişi sayısı'),
        ),
        migrations.AlterField(
            model_name='baskets',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
    ]
