# Generated by Django 5.0.1 on 2024-01-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0012_merge_0010_deletereservation_0011_deletereservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ddd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
