# Generated by Django 4.1.7 on 2024-01-09 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='additional_images',
        ),
    ]
