# Generated by Django 4.1.7 on 2024-01-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_alter_additionalimage_hotels'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotellocationmap',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Otel Konumu'),
        ),
    ]
