# Generated by Django 4.1.7 on 2024-01-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_alter_hotel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='star',
            field=models.IntegerField(blank=True, null=True, verbose_name='Otel Yıldızı'),
        ),
    ]
