# Generated by Django 4.1.7 on 2024-01-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_hotel_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotellocationmapbox',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Otel Konumu'),
        ),
    ]
