# Generated by Django 4.1.7 on 2024-01-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_alter_hotel_hotellocationmapbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hoteltitle',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Otel başlık'),
        ),
    ]
