# Generated by Django 4.1.7 on 2024-01-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_hotel_hoteltitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hoteltitle',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Otel başlık'),
        ),
    ]
