# Generated by Django 4.1.7 on 2024-01-15 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_alter_hotel_hoteltitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='İsim')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='email')),
                ('text', models.TextField(blank=True, max_length=500, null=True, verbose_name='yorum')),
                ('hotelscom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.hotel', verbose_name='otel yorumu')),
            ],
        ),
    ]
