# Generated by Django 4.1.7 on 2024-01-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0023_remove_comment_name_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='discount',
            field=models.IntegerField(blank=True, max_length=5, null=True, verbose_name='İndirim Oranı'),
        ),
    ]
